version: 2

jobs:
  build:
    docker:
      - image: rust:1.33
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: cargo build
      - run: cargo test
      - run: cargo fmt -- --check
